# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:

  - repo: local
    hooks:

      - id: black
        name: black
        entry: black isofit/
        language: system
        pass_filenames: false

      - id: isort
        name: isort
        entry: isort isofit/
        language: system
        pass_filenames: false
